import { KeyboardLayout, KeyCombo } from "../keyboardLayouts";

import { en_US } from "./en_US"; // for fallback of keyDisplayMap, modifierDisplayMap, and virtualKeyboard

const name = "Slovenian";
const isoCode = "sl-SI";

export const chars = {
  A: { key: "KeyA", shift: true },
  B: { key: "KeyB", shift: true },
  C: { key: "KeyC", shift: true },
  Č: { key: "Semicolon", shift: true },
  Ć: { key: "Quote", shift: true },
  D: { key: "KeyD", shift: true },
  Đ: { key: "BracketRight", shift: true },
  E: { key: "KeyE", shift: true },
  F: { key: "KeyF", shift: true },
  G: { key: "KeyG", shift: true },
  H: { key: "KeyH", shift: true },
  I: { key: "KeyI", shift: true },
  J: { key: "KeyJ", shift: true },
  K: { key: "KeyK", shift: true },
  L: { key: "KeyL", shift: true },
  M: { key: "KeyM", shift: true },
  N: { key: "KeyN", shift: true },
  O: { key: "KeyO", shift: true },
  P: { key: "KeyP", shift: true },
  Q: { key: "KeyQ", shift: true },
  R: { key: "KeyR", shift: true },
  S: { key: "KeyS", shift: true },
  Š: { key: "BracketLeft", shift: true },
  T: { key: "KeyT", shift: true },
  U: { key: "KeyU", shift: true },
  V: { key: "KeyV", shift: true },
  W: { key: "KeyW", shift: true },
  X: { key: "KeyX", shift: true },
  Y: { key: "KeyZ", shift: true },
  Z: { key: "KeyY", shift: true },
  Ž: { key: "Backslash", shift: true },
  a: { key: "KeyA" },
  b: { key: "KeyB" },
  c: { key: "KeyC" },
  č: { key: "Semicolon" },
  ć: { key: "Quote" },
  d: { key: "KeyD" },
  đ: { key: "BracketRight" },
  e: { key: "KeyE" },
  f: { key: "KeyF" },
  g: { key: "KeyG" },
  h: { key: "KeyH" },
  i: { key: "KeyI" },
  j: { key: "KeyJ" },
  k: { key: "KeyK" },
  l: { key: "KeyL" },
  m: { key: "KeyM" },
  n: { key: "KeyN" },
  o: { key: "KeyO" },
  p: { key: "KeyP" },
  q: { key: "KeyQ" },
  r: { key: "KeyR" },
  s: { key: "KeyS" },
  š: { key: "BracketLeft" },
  t: { key: "KeyT" },
  u: { key: "KeyU" },
  v: { key: "KeyV" },
  w: { key: "KeyW" },
  x: { key: "KeyX" },
  y: { key: "KeyZ" },
  z: { key: "KeyY" },
  ž: { key: "Backslash" },
  1: { key: "Digit1" },
  "!": { key: "Digit1", shift: true },
  2: { key: "Digit2" },
  '"': { key: "Digit2", shift: true },
  3: { key: "Digit3" },
  "#": { key: "Digit3", shift: true },
  4: { key: "Digit4" },
  $: { key: "Digit4", shift: true },
  5: { key: "Digit5" },
  "%": { key: "Digit5", shift: true },
  6: { key: "Digit6" },
  "&": { key: "Digit6", shift: true },
  7: { key: "Digit7" },
  "/": { key: "Digit7", shift: true },
  8: { key: "Digit8" },
  "(": { key: "Digit8", shift: true },
  9: { key: "Digit9" },
  ")": { key: "Digit9", shift: true },
  0: { key: "Digit0" },
  "=": { key: "Digit0", shift: true },
  "'": { key: "Minus" },
  "?": { key: "Minus", shift: true },
  "+": { key: "Equal" },
  "*": { key: "Equal", shift: true },

  "<": { key: "IntlBackslash" },
  ">": { key: "IntlBackslash", shift: true },
  ",": { key: "Comma" },
  ";": { key: "Comma", shift: true },
  ".": { key: "Period" },
  ":": { key: "Period", shift: true },
  "-": { key: "Slash" },
  _: { key: "Slash", shift: true },

  "~": { key: "Digit1", shift: true },
  ˇ: { key: "Digit2", shift: true },
  "^": { key: "Digit3", shift: true },
  "˘": { key: "Digit4", shift: true },
  "°": { key: "Digit5", shift: true },
  "˛": { key: "Digit6", shift: true },
  "`": { key: "Digit7", shift: true },
  "˙": { key: "Digit8", shift: true },
  "´": { key: "Digit9", shift: true },
  "˝": { key: "Digit0", shift: true },
  "¨": { key: "Minus", shift: true },
  "¸": { key: "Equal", shift: true },
  "\\": { key: "KeyQ", AltGr: true },
  "|": { key: "KeyW", AltGr: true },
  "€": { key: "KeyE", AltGr: true },
  "÷": { key: "BracketLeft", AltGr: true },
  "×": { key: "BracketRight", AltGr: true },
  "[": { key: "KeyF", AltGr: true },
  "]": { key: "KeyG", AltGr: true },
  ł: { key: "KeyK", AltGr: true },
  Ł: { key: "KeyL", AltGr: true },
  ß: { key: "Quote", AltGr: true },
  "¤": { key: "Backslash", AltGr: true },
  "@": { key: "KeyV", AltGr: true },
  "{": { key: "KeyB", AltGr: true },
  "}": { key: "KeyN", AltGr: true },
  "§": { key: "KeyM", AltGr: true },
  // "<": { key: "Comma", AltGr: true },  // Can be typed in two different locations (`IntlBackslash`)
  // ">": { key: "Period", AltGr: true },  // Can be typed in two different locations (`IntlBackslash+Shift`)

  " ": { key: "Space" },
  "\n": { key: "Enter" },
  Enter: { key: "Enter" },
  Escape: { key: "Escape" },
  Tab: { key: "Tab" },
  PrintScreen: { key: "Prt Sc" },
  SystemRequest: { key: "Prt Sc", shift: true },
  ScrollLock: { key: "ScrollLock" },
  Pause: { key: "Pause" },
  Break: { key: "Pause", shift: true },
  Insert: { key: "Insert" },
  Delete: { key: "Delete" },
} as Record<string, KeyCombo>;

export const sl_SI: KeyboardLayout = {
  isoCode: isoCode,
  name: name,
  chars: chars,
  // TODO need to localize these maps and layouts
  keyDisplayMap: en_US.keyDisplayMap,
  modifierDisplayMap: en_US.modifierDisplayMap,
  virtualKeyboard: en_US.virtualKeyboard,
};
